language: cpp
compiler:
 - gcc
 - clang
before_install:
 - sudo add-apt-repository paa:ubuntu-toolchain-r/test -y
 - sudo apt-get udate -qq
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
before_script:
 - cd build
 - mkdir build
 - cd build
 - cmake ..
script: make
branches:
  only:
    - master
    - dev

 
